// Code generation fixture: writes src/exports.generated.mjs from the exports it finds in src/slugify.mjs.
import { readFileSync, writeFileSync } from 'node:fs'
const src = readFileSync('src/slugify.mjs', 'utf8')
const names = [...src.matchAll(/export function (\w+)/g)].map((m) => m[1]).sort()
writeFileSync('src/exports.generated.mjs', `// GENERATED by scripts/gen-exports.mjs — do not edit.\nexport const EXPORTS = ${JSON.stringify(names)}\n`)
console.log(`gen-exports: ${names.length} export(s) -> ${names.join(', ')}`)
